<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Innovation.Shared">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Innovation.Shared.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
    </Reference>
    <Reference Include="NLayer">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\NLayer.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="Innovation.Script">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Innovation.Script.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="ShellFileDialogs">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\ShellFileDialogs.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\新创Unity 塔菲版\新创Unity 塔菲版_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>